name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose  --target=x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files:  target/debug/*
        draft: true
        fail_on_unmatched_files: true